#!/usr/bin/env -S deno run
import {
  consonants,
  randnum,
  random,
  textencoder,
  vowels,
  writeWord,
} from "./getseq"
const numbers = "0123456789"
const alphanum = (consonants + vowels).toUpperCase()

function magic(): string {
  return random(alphanum) + random(alphanum) + random(numbers)
}

const length = parseInt(Deno.args[0]) || 5

const specialPlace = randnum(length)

if (import.meta.main) {
  for (let i = 0; i < length; i++) {
    const prefix = i ? "-" : ""
    if (i === specialPlace) {
      Deno.stdout.writeSync(
        textencoder.encode(prefix + magic() + (prefix ? "" : "-")),
      )
    }
    writeWord(prefix)
  }
  console.log()
}
